=== balavart/The_Educational_Center/TheEducationalCenter/src/main/resources/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="TheEducationalCenter">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="studentProfiles">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
              <xs:element name="student" type="Student"/>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="UniqueIntegerIdOfStudent">
            <xs:selector xpath="student"/>
            <xs:field xpath="@id"/>
          </xs:unique>
          <xs:unique name="UniqueEmailOfStudent">
            <xs:selector xpath="student"/>
            <xs:field xpath="email"/>
          </xs:unique>
        </xs:element>

        <xs:element name="Info">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="curriculumProfiles">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="curriculum" type="CurriculumProfile" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueCurriculum">
                  <xs:selector xpath="curriculum"/>
                  <xs:field xpath="@id"/>
                </xs:unique>
                <xs:unique name="uniqueCurriculumTitle">
                  <xs:selector xpath="curriculum"/>
                  <xs:field xpath="title"/>
                </xs:unique>
              </xs:element>

              <xs:element name="courseProfiles">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="course" type="CourseProfile" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueCourse">
                  <xs:selector xpath="course"/>
                  <xs:field xpath="@id"/>
                </xs:unique>
                <xs:unique name="uniqueCourseTitle">
                  <xs:selector xpath="course"/>
                  <xs:field xpath="title"/>
                </xs:unique>
                <xs:unique name="uniqueCourseTaskId">
                  <xs:selector xpath=".//*"/>
                  <xs:field xpath="id"/>
                </xs:unique>
              </xs:element>

              <xs:element name="taskProfiles">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="task" type="TaskProfile" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
                <xs:unique name="uniqueTask">
                  <xs:selector xpath="task"/>
                  <xs:field xpath="@id"/>
                </xs:unique>
              </xs:element>
            </xs:sequence>
          </xs:complexType>

          <!--USING THIS KEY FOR REFERENCE -->
          <xs:key name="TaskItemKey">
            <xs:selector xpath=".//task"/>
            <xs:field xpath="@id"/>
          </xs:key>

          <xs:keyref name="TaskItemRef" refer="TaskItemKey">
            <xs:selector xpath=".//taskId"/>
            <xs:field xpath="id"/>
          </xs:keyref>

          <!--USING THIS KEY FOR REFERENCE -->
          <xs:key name="CourseItemKey">
            <xs:selector xpath=".//courseProfiles/course"/>
            <xs:field xpath="@id"/>
          </xs:key>

          <xs:keyref name="CourseItemRef" refer="CourseItemKey">
            <xs:selector xpath=".//courseProfiles/course"/>
            <xs:field xpath="id"/>
          </xs:keyref>

        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <!--USING THIS KEY FOR REFERENCE -->
    <xs:key name="StudentCurriculumKey">
      <xs:selector xpath=".//curriculumProfiles/curriculum"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="StudentCurriculumKeyRef" refer="StudentCurriculumKey">
      <xs:selector xpath=".//student"/>
      <xs:field xpath="curriculumId"/>
    </xs:keyref>

    <!--USING THIS KEY FOR REFERENCE -->
    <xs:key name="StudentTaskKey">
      <xs:selector xpath=".//Info/taskProfiles/task"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="StudentTaskKeyRef" refer="StudentTaskKey">
      <xs:selector xpath=".//studentProfiles/student/taskResults/task"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

  </xs:element>
  <!--_________________________________________________________________________________-->

  <xs:complexType name="Student">
    <xs:sequence>
      <xs:element name="fullName" type="LimitedString"/>
      <xs:element name="city" type="LimitedString"/>
      <xs:element name="email">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][a-z0-9_.\-]+@[a-z0-9_.\-]+\.[a-z]{2,5}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="startDate" type="xs:date"/>
      <xs:element name="contractSigned" type="xs:boolean"/>
      <xs:element name="curriculumId" type="xs:positiveInteger"/>
      <xs:element name="taskResults">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="task" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="status">
                    <xs:simpleType>
                      <xs:restriction base="xs:normalizedString">
                        <xs:enumeration value="The study has not begun"/>
                        <xs:enumeration value="In the process of studying"/>
                        <xs:enumeration value="Study completed"/>
                        <xs:enumeration value="Execution did not start"/>
                        <xs:enumeration value="In progress"/>
                        <xs:enumeration value="Is under verification"/>
                        <xs:enumeration value="Assignment Accepted"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="grade" type="PointScale" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>


  <xs:complexType name="CurriculumProfile">
    <xs:sequence>
      <xs:element name="title">
        <xs:simpleType>
          <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="Complete curriculum"/>
            <xs:enumeration value="Shortened curriculum"/>
            <xs:enumeration value="Special curriculum 1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="author" type="LimitedString"/>
      <xs:element name="creationDate" type="xs:date"/>
      <xs:element name="courseList">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="course" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="id">
                    <xs:simpleType>
                      <xs:restriction base="xs:positiveInteger"/>
                    </xs:simpleType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueCourseInCurr">
          <xs:selector xpath=".//course"/>
          <xs:field xpath="id"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger"/>
  </xs:complexType>


  <xs:complexType name="CourseProfile">
    <xs:sequence>
      <xs:element name="title">
        <xs:simpleType>
          <xs:restriction base="xs:normalizedString">
            <xs:enumeration value='Course "Overview of Eclipse IDE"'/>
            <xs:enumeration value='Course "Java Basics"'/>
            <xs:enumeration value='Course "Java - extended capabilities"'/>
            <xs:enumeration value='Course "XML"'/>
            <xs:enumeration value='Course "XSLT and XPath"'/>
            <xs:enumeration value='Course "Struts Framework Technology"'/>
            <xs:enumeration value='Course "Software manufacturing process"'/>
            <xs:enumeration value='Course "Software development process"'/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="author" type="LimitedString"/>
      <xs:element name="creationDate" type="xs:date"/>
      <xs:element name="courseTasksList">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="taskId" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="id">
                    <xs:simpleType>
                      <xs:restriction base="xs:positiveInteger"/>
                    </xs:simpleType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="id" type="xs:positiveInteger"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueCourseTask">
          <xs:selector xpath="taskId"/>
          <xs:field xpath="@id"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>


  <xs:complexType name="TaskProfile">
    <xs:sequence>
      <xs:element name="title" type="LimitedString"/>
      <xs:element name="duration" type="xs:positiveInteger"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:normalizedString">
          <xs:pattern value="Theory|Practice"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:simpleType name="PointScale">
    <xs:restriction base="xs:int">
      <xs:pattern value="[1-5]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LimitedString">
    <xs:restriction base="xs:normalizedString">
      <xs:minLength value="1"/>
      <xs:maxLength value="70"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== balavart/The_Educational_Center/TheEducationalCenter/src/main/resources/temp.xml
<TheEducationalCenter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Report.xsd">

  <studentProfiles>
    <student id="1">
      <fullName>string</fullName>
      <city>string</city>
      <email>asd@gmail.com</email>
      <startDate>2008-09-29</startDate>
      <contractSigned>true</contractSigned>
      <curriculumId>1</curriculumId>
      <taskResults>
        <!--1 or more repetitions:-->
        <taskResult>
          <status>Assignment Accepted</status>
          <!--Optional:-->
          <grade>3</grade>
        </taskResult>

      </taskResults>
    </student>
  </studentProfiles>

  <info>
    <curriculumProfiles>
      <!--1 or more repetitions:-->
      <curriculum id="1">
        <title>Shortened curriculum</title>
        <author>string</author>
        <creationDate>2006-08-19+04:00</creationDate>
        <courseList>
          <!--1 or more repetitions:-->
          <course>
            <id>1</id>
          </course>
        </courseList>
      </curriculum>
    </curriculumProfiles>

    <courseProfiles>
      <!--1 or more repetitions:-->
      <course id="1">
        <title>Course "Struts Framework Technology"</title>
        <author>string</author>
        <creationDate>2013-05-22+04:00</creationDate>
        <courseTasksList>
          <!--1 or more repetitions:-->
          <taskId id="1">
            <id>1</id>
          </taskId>
        </courseTasksList>
      </course>
    </courseProfiles>

    <taskProfiles>
      <!--Zero or more repetitions:-->
      <task id="1" type="Theory">
        <title>string</title>
        <duration>201</duration>
      </task>
    </taskProfiles>
  </info>

</TheEducationalCenter>
